version: '3.3'
 
services:
  db:
    image: postgres
    env_file:
      - .database.env
    volumes:
      - data:/var/lib/postgresql/data/
  web:
    build: .
    command: sh -c "
      python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8000"
    container_name: django_test
    volumes:
      - static_volume:/app/storage  
    env_file:
      - .env

    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  data:
  static_volume:
